[project]
name = "elden-ring"
version = "0.1.0"
description = "Add a short description here"
authors = ["Clouds Flowing <clouds.flowing@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "win-64"]

[tasks]
init = { depends_on = ["init-git", "build-dotnet", "init-clr-typings", "init-tauri"] }
init-git = "git submodule update --init --recursive && sed 's|${PWD}|'$(pwd)'|g' python.env.in | tee python.env && python scripts/00-a-patch.py"
init-tauri = "yarn --cwd tauri-app install && pixi run python scripts/04-tune.py"
# this only need in non-windows
init-oodle = "bash scripts/00-c-init_oodle.sh"
init-clr-typings = { cmd = "dotnet publish -c Release vendor/pythonnet-stub-generator/csharp/PythonNetStubGenerator && python scripts/00-b-gen_typings.py", depends_on = ["build-dotnet"] }
build-dotnet = "dotnet build && dotnet publish -c Release libs/UnpackHelper"
unpack = { cmd = "python scripts/unpack.py", depends_on = ["build-dotnet"] }
dev-tauri = "yarn --cwd tauri-app tauri dev"
clean-dotnet = "rm -rf libs/UnpackHelper/bin libs/UnpackHelper/obj vendor/SoulsFormatsNEXT/SoulsFormats/bin vendor/SoulsFormatsNEXT/SoulsFormats/obj vendor/WitchyBND/StudioUtils/bin vendor/WitchyBND/StudioUtils/obj vendor/WitchyBND/WitchyFormats/bin vendor/WitchyBND/WitchyFormats/obj"

[dependencies]
python = "~=3.12.5"
ipykernel = "~=6.29"
pandas = "~=2.2"
pyarrow = "~=17.0"
polars = "~=1.7"
pythonnet = "~=3.0"
tqdm = "~=4"
streamlit = "~=1.38"
cmake = ">=3.30.3,<4"

[pypi-dependencies]
polars-distance = ">=0.4.3, <0.5"
imageio = ">=2.35.1,<3"
