[project]
name = "elden-ring"
version = "0.1.0"
description = "Add a short description here"
authors = ["Clouds Flowing <clouds.flowing@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = "~=3.12.5"
ipykernel = "~=6.29"
pandas = "~=2.2"
pyarrow = "~=17.0"
polars = "~=1.7"
pythonnet = "~=3.0"
tqdm = "~=4"
streamlit = "~=1.38"
