[project]
name = "elden-ring"
version = "0.1.0"
description = "Add a short description here"
authors = ["Clouds Flowing <clouds.flowing@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = ">=3.12.5,<3.13"
pydantic = ">=1.8,<2" # this is required since erdb require <2

[pypi-dependencies]
erdb = "*"
